// Generated by CoffeeScript 1.8.0
(function() {
  var GithubEventEmitter;

  GithubEventEmitter = require("./ee/github").GithubEventEmitter;

  module.exports.PROVIDER_URLS = {
    github: function(id, state) {
      return "https://github.com/login/oauth/authorize?client_id=" + id + "&state=" + state;
    }
  };

  module.exports.CLIENT_IDS = {
    "github": process.env.GITHUB_CLIENT_ID
  };

  module.exports.CLIENT_SECRETS = {
    "github": process.env.GITHUB_CLIENT_SECRET
  };

  module.exports.EVENT_EMITTERS = {
    "github": GithubEventEmitter
  };

}).call(this);
