// Generated by CoffeeScript 1.8.0
(function() {
  var CLIENT_IDS, EVENT_EMITTERS, PROVIDER_URLS, auth_callback, auth_callback_template, auth_provider_redirect, _ref;

  _ref = require("./config"), CLIENT_IDS = _ref.CLIENT_IDS, PROVIDER_URLS = _ref.PROVIDER_URLS, EVENT_EMITTERS = _ref.EVENT_EMITTERS;

  auth_provider_redirect = function(req, res) {
    var URL, provider;
    provider = req.param("provider");
    URL = PROVIDER_URLS[provider](CLIENT_IDS[provider], JSON.parse(req.query.opts)["state"]);
    res.redirect(URL);
    return res.send();
  };

  auth_callback_template = function(o) {
    return "<script>\n  window.opener.postMessage('" + (JSON.stringify(o)) + "',\n                            '" + process.env.OAUTH_REDIRECT_URL + "')\n</script>";
  };

  auth_callback = function(req, res) {
    var cb, provider, provider_event_emitter;
    provider = req.param("provider");
    provider_event_emitter = EVENT_EMITTERS[provider];
    cb = function(provider_response) {
      var str;
      str = '';
      provider_response.on('data', function(chunk) {
        return str += chunk;
      });
      return provider_response.on('end', function() {
        return provider_event_emitter.emit("receiveAccessToken", req, str, function(o) {
          var s;
          console.log("provider_event_emitter");
          s = auth_callback_template(o);
          console.log(s);
          return res.send(s);
        });
      });
    };
    return provider_event_emitter.emit("requestToken", req, res, cb);
  };

  module.exports.auth_provider_redirect = auth_provider_redirect;

  module.exports.auth_callback = auth_callback;

}).call(this);
